"""
Main entry point for the Cipher & Decipher Benchmark.
"""

import asyncio
import argparse
import logging
import sys
from pathlib import Path
from datetime import datetime

TASK_ROOT = Path(__file__).resolve().parent


def find_project_root() -> Path:
    for parent in TASK_ROOT.parents:
        if (parent / "cli.py").exists():
            return parent
    return TASK_ROOT.parents[-1]


PROJECT_ROOT = find_project_root()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

# Add src to path after the project root so shared modules (e.g., /models) take precedence
SRC_PATH = Path(__file__).parent / "src"
if str(SRC_PATH) not in sys.path:
    sys.path.append(str(SRC_PATH))

from src.benchmark_runner import BenchmarkRunner
from configs.locator import resolve_config_path

# Set up logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler('benchmark.log')
    ]
)
logger = logging.getLogger(__name__)


def resolve_path(path_str: str) -> str:
    """Resolve path relative to CWD or repository root (with dataset fallback)."""
    path = Path(path_str)

    candidates = []
    if path.is_absolute():
        candidates.append(path)
        relative = Path(*path.parts[1:]) if len(path.parts) > 1 else Path(path.name)
    else:
        relative = path

    candidates.extend([
        TASK_ROOT / relative,
        TASK_ROOT / "datasets" / relative.name,
        PROJECT_ROOT / relative,
        PROJECT_ROOT / "test" / "datasets" / relative.name,
        relative,
    ])

    for candidate in candidates:
        if candidate.exists():
            return str(candidate.resolve())

    return str(path)

async def main():
    """Main function."""
    parser = argparse.ArgumentParser(
        description="Cipher & Decipher Benchmark"
    )
    parser.add_argument("--config", default="config.yaml", 
                       help="Path to config file")
    parser.add_argument("--models", nargs="+", 
                       help="Models to benchmark (default: all available)")
    parser.add_argument("--samples", type=int, 
                       help="Number of samples per task")
    parser.add_argument("--test-file", type=str, default=None,
                       help="Load test cases from JSON file instead of generating (generated by generate_dataset.py)")
    parser.add_argument("--verbose", "-v", action="store_true", 
                       help="Enable verbose logging (prints prompts, responses, golden answers, and extracted answers)")
    parser.add_argument("--debug", action="store_true", 
                       help="Enable debug logging")
    parser.add_argument("--save-responses", action="store_true",
                       help="Save all prompts and model responses to log file")
    parser.add_argument("--response-log", type=str, default=None,
                       help="Path to response log file (default: logs/responses_TIMESTAMP.json)")
    parser.add_argument("--prompt-style", choices=['basic', 'detailed', 'step_by_step'], 
                       help="Override default prompt style for all tasks")
    parser.add_argument("--restricted-reasoning", action="store_true",
                       help="Use restricted thinking prompts that discourage heavy reasoning")
    # parser.add_argument("--experiment-id", type=str, default=None,
    #                    help="Experiment identifier for unified file naming (default: current date in MMDD format)")
    
    args = parser.parse_args()

    if not Path(args.config).is_absolute():
        args.config = resolve_config_path("cipher_decipher", args.config)
    if args.test_file:
        args.test_file = resolve_path(args.test_file)
    
    # Set logging level
    if args.debug:
        logging.getLogger().setLevel(logging.DEBUG)
    
    try:
        # Initialize benchmark runner
        runner = BenchmarkRunner(
            config_path=args.config,
            save_responses=args.save_responses,
            response_log_file=args.response_log,
            verbose=args.verbose,
            restricted_reasoning=args.restricted_reasoning,
            allowed_models=set(args.models) if args.models else None,
            # experiment_id=args.experiment_id
        )
        
        # Override prompt style if specified via command line
        if args.prompt_style:
            runner.default_prompt_style = args.prompt_style
            runner.per_task_styles = {}  # Clear per-task styles to use the override
            logger.info(f"Overriding prompt style to: {args.prompt_style}")
        
        if not runner.models:
            logger.error("No models available. Please check your configuration and API keys.")
            return
        
        logger.info(f"Available models: {list(runner.models.keys())}")
        logger.info(f"Using prompt style: {runner.default_prompt_style}")
        
        # Log mode information
        if args.verbose:
            logger.info("Verbose mode enabled - will print detailed information for each task")
        if args.save_responses:
            log_file = args.response_log if args.response_log else f"logs/responses_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
            logger.info(f"Response logging enabled - saving to: {log_file}")
        
        # Log test data source
        if args.test_file:
            logger.info(f"Loading test data from: {args.test_file}")
        else:
            logger.info("Generating new test data")
        
        # Run benchmark
        results = await runner.run_benchmark(
            models=args.models,
            num_samples=args.samples,
            test_file=args.test_file
        )
        
        # Print summary
        runner.print_summary(results)
        
        logger.info("Benchmark completed successfully!")
        
        # Print log file location if responses were saved
        if args.save_responses and runner.response_logger:
            print(f"\nDetailed logs saved to:")
            print(f"  JSON: {runner.response_logger.log_file}")
            print(f"  TXT:  {runner.response_logger.log_file.with_suffix('.txt')}")
        
    except Exception as e:
        logger.error(f"Benchmark failed: {e}")
        import traceback
        traceback.print_exc()
        raise


if __name__ == "__main__":
    asyncio.run(main())
